apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: unicorn
data:
  VITE_BACKEND_URL: "http://ripon.your-domain.com"
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:K67B1vYpdsxaFarl36RciYKcknOEUQzFMGYLRbT0EFg="
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "frontend.your-domain.com"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  PHP_CLI_SERVER_WORKERS: "4"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"
