---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: laravel-secret
  namespace: unicorn
data:
  DB_DATABASE:  bGFyYXZlbA== #laravel
  DB_USERNAME:  bGFyYXZlbA== #laravel
  DB_PASSWORD: c2VjcmV0 #secret

---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: unicorn
data:
  VITE_BACKEND_URL: "http://ripon.your-domain.com"
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:K67B1vYpdsxaFarl36RciYKcknOEUQzFMGYLRbT0EFg="
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "frontend.your-domain.com"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  APP_MAINTENANCE_DRIVER: "file"
  PHP_CLI_SERVER_WORKERS: "4"
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-backend
  labels:
    app: laravel-backend
  namespace: unicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-backend
  template:
    metadata:
      labels:
        app: laravel-backend
    spec:
      containers:
        - name: laravel-backend
          image: syedkamruzzaman/uni_backend:17
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            # - name: DB_DATABASE
            #   value: "laravel"
            # - name: DB_USERNAME
            #   value: "laravel"
            # - name: DB_PASSWORD
            #   value: "secret"
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: laravel-secret
                           
        - name: nginx-backend
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-backend
              subPath: default.conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
           
      volumes:
        - name: nginx-config-backend
          configMap:
            name: nginx-config-backend
       

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-backend
  namespace: unicorn
spec:
  selector:
    app: laravel-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
