apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: unicorn
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ripon.syed-kamruzzaman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5173
    - host: ripon3.syed-kamruzzaman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravel-backend
                port:
                  number: 80
  tls:
    - hosts:
        - ripon.syed-kamruzzaman.com
        - ripon3.syed-kamruzzaman.com
      secretName: unicorn-app-tls
