name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current frontend tag
        id: get-frontend-tag
        run: |
          TAG=$(curl -s https://hub.docker.com/v2/repositories/syedkamruzzaman/uni_frontend/tags | jq -r '.results[0].name')
          echo "Current frontend tag: $TAG"
          NEW_TAG=$((10#$TAG + 1))
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile_frontend
          push: true
          tags: |
            syedkamruzzaman/uni_frontend:${{ env.new_tag }}

      - name: Get current backend tag
        id: get-backend-tag
        run: |
          TAG=$(curl -s https://hub.docker.com/v2/repositories/syedkamruzzaman/uni_backend/tags | jq -r '.results[0].name')
          echo "Current backend tag: $TAG"
          NEW_TAG=$((10#$TAG + 1))
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile_Backend
          push: true
          tags: |
            syedkamruzzaman/uni_backend:${{ env.new_tag }}
